### ISSUE TITLE
raid frame keep disaprearing and lua errors

### ISSUE THREAD

**Issue by neuvo123** [jordonwow/bigdebuffs#556]
playing battlegrounds raidframes keep disappear and get this lua error

reload gets them back but soon the lua error comes again and frames disappear

I heal with mouseover macros on raidframes when this happens I think

13x [ADDON_ACTION_BLOCKED] AddOn 'BigDebuffs' tried to call the protected function 'CompactRaidFrame1:SetPoint()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetPoint'
[string "@FrameXML/FlowContainer.lua"]:172: in function `FlowContainer_DoLayout'
[string "@FrameXML/FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:174: in function `LayoutFrames'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:128: in function `TryUpdate'
[string "@Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameContainer.lua"]:57: in function <...actRaidFrames/Blizzard_CompactRaidFrameContainer.lua:50>

**Comment by Wowfan333** [comment]
So annoying at least I know which addon cause it ... the only addon I really need and can't disable it xd....

**Comment by Bigbigjoy** [comment]
I'm having the same issue on Raid Groups. But less than the last update.

**Comment by hail2skins** [comment]
My raid frames also do commonly disappear.   As reported above, less than the previous release, but still happens.   As a healer who heals from clicks on frames, this is game breaking so I have had to remove the best addon in the game.   It works fine with party frames.   It is ONLY Raid frames that break.

**Comment by Jestter** [comment]
I think it occurs more often when someone join or leaves the raid group

**Comment by hail2skins** [comment]
Not for me Jestter as though it does happen in random BGs, it also happens in rated BGs where my group is fixed.   I suspect it has something to do with spells from some classes.   Perhaps Evoker or something where when they hit something breaks.  No idea really.   I see it was updated yesterday so will try it again to see if it is better and hope.

**Comment by BradCOnGitHub** [comment]
It's not fixed. 

It doesn't even take someone leaving the raid group. Someone going offline/online will break it all too.
